### PR TITLE
expose GetCallerIdentity as data source

### PR DESCRIPTION
**Pull request by tareqhs**
`GetCallerIdentity` is already used internally in `client.go` for supporting `alicloud_account` data provider. Expose the whole caller identity structure as a data provider for general use.
The existing `alicloud_account` should be deprecated in favor of the new data provider.

### CODE REVIEW

**Comment by xiaozhu36** [comment]
HI @tareqhs Thanks for your contribution. Can you add testcases and docs for this PR?

**Comment by tareqhs** [comment]
Hi @xiaozhu36 , of course i'm on it. Meanwhile feel free to comment on the main code.

**Comment by tareqhs** [comment]
hi @xiaozhu36, test and doc added.

**Comment by tareqhs** [comment]
@xiaozhu36 when is this expected to be released?

**Comment by xiaozhu36** [comment]
@tareqhs It will be released on Saturday morning Beijing time.

**Pull request merged**
